routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\TermsOfServiceController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/current_terms_of_service', [TermsOfServiceController::class, 'current'])->name('terms_of_service.current');

Route::group([
    'middleware' => ['auth', 'verified'],
], function () {
    Route::get('/', function () {
        return redirect(\App\Providers\RouteServiceProvider::HOME);
    });

    Route::get('dashboard', [HomeController::class, 'dashboard'])->name('dashboard');
    Route::put('users/{user}/unverify', [UsersController::class, 'unverify'])->name('users.unverify');
    Route::resource('users', UsersController::class)
        ->only(['index', 'update', 'destroy', 'edit']);

    Route::post('terms_of_service/accept_new', [TermsOfServiceController::class, 'acceptNewTermsOfService'])->name('terms_of_service.accept_new');

    Route::resource('terms_of_service', TermsOfServiceController::class);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'phone_number',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $appends = [
        'action_urls',
        'has_verified_email',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'terms_of_service_accepted_at' => 'datetime',
    ];

    /**
     * @return bool
     */
    public function getHasVerifiedEmailAttribute()
    {
        return $this->hasVerifiedEmail();
    }

    /**
     * A list of urls for actions that can be performed on the user.
     *
     * @return array
     */
    public function getActionUrlsAttribute()
    {
        return [
            'edit' => route('users.edit', $this->id),
            'destroy' => route('users.destroy', $this->id),
            'unverify' => route('users.unverify', $this->id),
        ];
    }

    /**
     * A custom scope to be used for filtering on the users dashboard.
     *
     * @param $query
     * @param string $term
     */
    public function scopeSearch($query, string $term)
    {
        $query->where(function ($q) use ($term) {
            $q->orWhere('email', 'LIKE', '%'.$term.'%')
                ->orWhere('name', 'LIKE', '%'.$term.'%')
                ->orWhere('phone_number', 'LIKE', '%'.$term.'%');
        });
    }

    /**
     * Unverifies the email of the user.
     */
    public function unverify()
    {
        $this->forceFill(['email_verified_at' => null])
            ->save();
    }

    /**
     * The terms of service accepted by the user.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function acceptedTermsOfService()
    {
        return $this->belongsTo(TermsOfService::class, 'terms_of_service_id');
    }

    public function hasAcceptedLatestTermsOfService()
    {
        return $this->acceptedTermsOfService->id === TermsOfService::getMostRecentPublished()->id;
    }

    public function acceptTermsOfService(TermsOfService $termsOfService)
    {
        $this->forceFill([
            'terms_of_service_id' => $termsOfService->id,
            'terms_of_service_accepted_at' => now(),
        ])->save();
    }

    public function changeEmail(string $email)
    {
        $this->forceFill([
            'email_verified_at' => null,
            'email' => $email,
        ])->save();

        $this->sendEmailVerificationNotification();
    }

    public function changePassword(string $password)
    {
        $this->forceFill([
            'password' => Hash::make($password),
        ])->save();
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UpdateUserRequest;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UsersController extends Controller
{
    /**
     * @param Request $request
     * @return User[]|Collection
     */
    public function index(Request $request)
    {
        if ($search = trim($request->search)) {
            return User::search($search)->get();
        }

        return User::all();
    }

    /**
     * @param User $user
     * @return View
     */
    public function edit(User $user): View
    {
        return view('users.edit', [
            'user' => $user,
        ]);
    }

    /**
     * @param UpdateUserRequest $request
     * @param User $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateUserRequest $request, User $user)
    {
        $messages = [];

        $user->update($request->only(['name', 'phone_number']));
        $messages[] = 'Changes have been saved.';

        if ($user->email !== $request->email) {
            $user->changeEmail($request->email);
            $messages[] = 'A verification email has been sent to the new address.';
        }

        if ($request->password && ! Hash::check($request->password, $user->password)) {
            $user->changePassword($request->password);
            $messages[] = 'The password has been changed.';
        }

        return back()->with('success', $messages);
    }

    /**
     * @param User $user
     * @throws \Exception
     */
    public function destroy(User $user)
    {
        $user->delete();
    }

    /**
     * @param User $user
     * @return User
     */
    public function unverify(User $user)
    {
        $user->unverify();

        return $user;
    }
}

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Edit user') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('users.update', $user) }}">
                            @method('PUT')
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text"
                                           class="form-control @error('name') is-invalid @enderror" name="name"
                                           value="{{ old('name', $user->name) }}" required autocomplete="name"
                                           autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="phone_number"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Phone number') }}</label>

                                <div class="col-md-6">
                                    <input id="phone_number" type="text"
                                           class="form-control @error('phone_number') is-invalid @enderror"
                                           name="phone_number" value="{{ old('phone_number', $user->phone_number) }}"
                                           autocomplete="phone_number">

                                    @error('phone_number')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email"
                                       class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email"
                                           class="form-control @error('email') is-invalid @enderror" name="email"
                                           value="{{ old('email', $user->email) }}" required autocomplete="email">
                                    <span>
                                        {{ __('Changing the email will send a verification email to the new address. The user will NOT be able to log in with the original email.') }}
                                    </span><br>

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-md-4"></div>
                                <div class="col-md-6">

                                    <h5 class="text-center ">Change password</h5>

                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password"
                                       class="col-md-4 col-form-label text-md-right">{{ __('New Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password"
                                           class="form-control @error('password') is-invalid @enderror" name="password"
                                           autocomplete="new-password">

                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password-confirm"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Confirm New Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password-confirm" type="password" class="form-control"
                                           name="password_confirmation" autocomplete="new-password">
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Save') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection