routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\TermsOfServiceController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/current_terms_of_service', [TermsOfServiceController::class, 'current'])->name('terms_of_service.current');

Route::group([
    'middleware' => ['auth', 'verified'],
], function () {
    Route::get('/', function () {
        return redirect(\App\Providers\RouteServiceProvider::HOME);
    });

    Route::get('dashboard', [HomeController::class, 'dashboard'])->name('dashboard');
    Route::put('users/{user}/unverify', [UsersController::class, 'unverify'])->name('users.unverify');
    Route::resource('users', UsersController::class)
        ->only(['index', 'update', 'destroy', 'edit']);

    Route::post('terms_of_service/accept_new', [TermsOfServiceController::class, 'acceptNewTermsOfService'])->name('terms_of_service.accept_new');

    Route::resource('terms_of_service', TermsOfServiceController::class);
});

app/Models/TermsOfService.php
<?php

namespace App\Models;

use App\Jobs\NotifyUsersAboutTermsOfServiceChanges;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TermsOfService extends Model
{
    use HasFactory;

    protected $fillable = [
        'administrative_name',
        'content',
    ];

    protected $dates = [
        'publication_date',
    ];

    public function isPublished()
    {
        return ! is_null($this->publication_date);
    }

    /**
     * Publishes the terms of service
     * This sends a notification to users that haven't accepted the current tos (all of them).
     */
    public function publish()
    {
        $this->forceFill(['publication_date' => now()])->save();
        dispatch(new NotifyUsersAboutTermsOfServiceChanges());
    }

    public static function getMostRecentPublished()
    {
        return self::whereNotNull('publication_date')
            ->orderBy('publication_date', 'desc')
            ->orderBy('id', 'desc')
            ->firstOrFail();
    }
}

app/Http/Controllers/TermsOfServiceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AcceptNewTermsOfServiceRequest;
use App\Http\Requests\TermsOfServiceStoreRequest;
use App\Http\Requests\TermsOfServiceUpdateRequest;
use App\Models\TermsOfService;
use Illuminate\Contracts\Auth\Authenticatable;

class TermsOfServiceController extends Controller
{
    public function index()
    {
        $items = TermsOfService::all();

        return view('terms_of_service.index', [
            'items' => $items,
        ]);
    }

    public function create()
    {
        return view('terms_of_service.create');
    }

    public function store(TermsOfServiceStoreRequest $request)
    {
        TermsOfService::create($request->only(['administrative_name', 'content']));

        return redirect()
            ->route('terms_of_service.index')
            ->with('success', ['Terms of service created!']);
    }

    public function show(TermsOfService $termsOfService)
    {
        return view('terms_of_service.show', [
            'item' => $termsOfService,
        ]);
    }

    public function edit(TermsOfService $termsOfService)
    {
        if ($termsOfService->isPublished()) {
            abort(401, "Can't edit publised terms.");
        }

        return view('terms_of_service.edit', [
            'item' => $termsOfService,
        ]);
    }

    public function update(TermsOfServiceUpdateRequest $request, TermsOfService $termsOfService)
    {
        if ($termsOfService->isPublished()) {
            abort(401, "Can't edit publised terms.");
        }

        $termsOfService->update($request->only(['administrative_name', 'content']));

        if ($request->publish) {
            $termsOfService->publish();

            return redirect()->route('terms_of_service.index')
                ->with('success', ['Terms of service updated and published!']);
        }

        return redirect()->route('terms_of_service.index')
            ->with('success', ['Terms of service updated!']);
    }

    public function destroy(TermsOfService $termsOfService)
    {
        if ($termsOfService->isPublished()) {
            abort(401, "Can't delete published terms.");
        }

        $termsOfService->delete();

        return back()->with(['success' => ['Terms of service deleted']]);
    }

    /**
     * Show the current terms of service.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function current()
    {
        $termsOfService = TermsOfService::getMostRecentPublished();

        return view('terms_of_service.show', [
            'item' => $termsOfService,
        ]);
    }

    /**
     * Make sure that the accepted tos is the current tos before updating the user.
     *
     * @param AcceptNewTermsOfServiceRequest $request
     * @param Authenticatable $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function acceptNewTermsOfService(AcceptNewTermsOfServiceRequest $request, Authenticatable $user)
    {
        if ((int) $request->terms_of_service_id !== TermsOfService::getMostRecentPublished()->id) {
            return redirect()->route('terms_of_service.current')->withErrors(['terms_of_service_id' => 'You are not accepting the latest terms of service. Try again.']);
        }

        $user->acceptTermsOfService(TermsOfService::getMostRecentPublished());

        return back()->with(['success' => ['You\'ve accepted the new terms of service']]);
    }
}

resources/views/terms_of_service/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Create Terms') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('terms_of_service.store') }}">
                            @csrf
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Administrative name') }}</label>

                                <div class="col-md-6">
                                    <input id="administrative_name" type="text"
                                           class="form-control @error('administrative_name') is-invalid @enderror" name="administrative_name"
                                           value="{{ old('administrative_name') }}" required autocomplete="name"
                                           autofocus>

                                    @error('administrative_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="content"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Content') }}</label>

                                <div class="col-md-6">
                                    <textarea id="content"
                                           class="form-control @error('content') is-invalid @enderror"
                                              name="content">{{ old('content') }}</textarea>
                                    @error('content')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Create') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/terms_of_service/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Edit Terms') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('terms_of_service.update', $item) }}">
                            @method('PUT')
                            @csrf
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Administrative name') }}</label>

                                <div class="col-md-6">
                                    <input id="administrative_name" type="text"
                                           class="form-control @error('administrative_name') is-invalid @enderror" name="administrative_name"
                                           value="{{ old('administrative_name', $item->administrative_name) }}" required autocomplete="name"
                                           autofocus>

                                    @error('administrative_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="content"
                                       class="col-md-4 col-form-label text-md-right">{{ __('Content') }}</label>

                                <div class="col-md-6">
                                    <textarea id="content"
                                           class="form-control @error('content') is-invalid @enderror"
                                              name="content">{{ old('content', $item->content) }}</textarea>
                                    @error('content')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Update') }}
                                    </button>
                                    <button type="submit" name="publish" value="1" class="btn btn-primary">
                                        {{ __('Update and publish') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/terms_of_service/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="mb-4">
            <div class="row">
                <div class="col">
                    <a href="{{ route('terms_of_service.create') }}" class="btn btn-primary">Add new terms</a>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Publication date</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($items as $item)
                        <tr>
                            <td>{{ $item->id }}</td>
                            <td>{{ $item->administrative_name }}</td>
                            <td>{{ $item->publication_date ? $item->publication_date->format('Y-m-d H:i') : 'not published' }}</td>
                            <td>
                                @if($item->publication_date)
                                <a class="btn btn-sm btn-secondary" href="{{ route('terms_of_service.show', $item) }}">View</a>
                                @else
                                <a class="btn btn-sm btn-primary" href="{{ route('terms_of_service.edit', $item) }}">Edit</a>
                                <form method="POST" action="{{ route('terms_of_service.destroy', $item) }}" style="display: inline">
                                    @csrf
                                    @method("DELETE")
                                    <button class="btn btn-sm btn-danger" >Delete</button>
                                </form>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/terms_of_service/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <div class="row justify-content-center">
            <div class="col">
                <h4>Published: {{ $item->publication_date->toISOString() }}</h4>
                <p>{!! $item->content !!}</p>
            </div>
        </div>
    </div>
@endsection