routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\TermsOfServiceController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/current_terms_of_service', [TermsOfServiceController::class, 'current'])->name('terms_of_service.current');

Route::group([
    'middleware' => ['auth', 'verified'],
], function () {
    Route::get('/', function () {
        return redirect(\App\Providers\RouteServiceProvider::HOME);
    });

    Route::get('dashboard', [HomeController::class, 'dashboard'])->name('dashboard');
    Route::put('users/{user}/unverify', [UsersController::class, 'unverify'])->name('users.unverify');
    Route::resource('users', UsersController::class)
        ->only(['index', 'update', 'destroy', 'edit']);

    Route::post('terms_of_service/accept_new', [TermsOfServiceController::class, 'acceptNewTermsOfService'])->name('terms_of_service.accept_new');

    Route::resource('terms_of_service', TermsOfServiceController::class);
});

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\Support\Renderable;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
    }

    /**
     * Show the application dashboard.
     *
     * @return Renderable
     */
    public function dashboard()
    {
        return view('home.dashboard');
    }
}

resources/views/home/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <div class="container" id="users-list">
        <form class="mb-4" @submit.prevent="search(searchTerm)">

            <div class="row">
                <div class="col">
                    <input type="text" class="form-control" v-model="searchTerm" placeholder="">
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-primary">Search</button>
                </div>
            </div>
        </form>

        <div class="row justify-content-center">
            <div class="col">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Email</th>
                        <th>Phone Number</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody is="transition-group" name="list">
                    <tr v-for="user in users" :key="user.id" class="list-item">
                        <td>@{{ user.id }}</td>
                        <td>@{{ user.email }}</td>
                        <td>@{{ user.phone_number }}</td>
                        <td>
                            <a class="btn btn-sm btn-primary" :href="user.action_urls.edit">Edit</a>
                            <button class="btn btn-sm btn-danger" @click="deleteUser(user)">Delete</button>
                            <button class="btn btn-sm btn-warning"
                                    v-if="user.has_verified_email"
                                    @click="unverify(user)">Unverify
                            </button>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            initUsersList('{{ route('users.index') }}')
        })
    </script>
@endsection