routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\TermsOfServiceController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/current_terms_of_service', [TermsOfServiceController::class, 'current'])->name('terms_of_service.current');

Route::group([
    'middleware' => ['auth', 'verified'],
], function () {
    Route::get('/', function () {
        return redirect(\App\Providers\RouteServiceProvider::HOME);
    });

    Route::get('dashboard', [HomeController::class, 'dashboard'])->name('dashboard');
    Route::put('users/{user}/unverify', [UsersController::class, 'unverify'])->name('users.unverify');
    Route::resource('users', UsersController::class)
        ->only(['index', 'update', 'destroy', 'edit']);

    Route::post('terms_of_service/accept_new', [TermsOfServiceController::class, 'acceptNewTermsOfService'])->name('terms_of_service.accept_new');

    Route::resource('terms_of_service', TermsOfServiceController::class);
});

resources/views/layouts/_accept_terms_of_service_prompt.blade.php
<div class="alert alert-danger">
    Please accept the new terms of service. <br>
    <a href="{{ route('terms_of_service.show', auth()->user()->acceptedTermsOfService) }}">Terms you've accepted on {{ auth()->user()->terms_of_service_accepted_at->toIsoString() }} (old)</a> <br>
    <a href="{{ route('terms_of_service.current') }}">New terms that you must read and accept, published on {{ \App\Models\TermsOfService::getMostRecentPublished()->publication_date->toIsoString() }} (new)</a> <br>
    <form method="POST" action="{{ route('terms_of_service.accept_new') }}" >
        @csrf
        <input type="hidden" name="terms_of_service_id" value="{{ \App\Models\TermsOfService::getMostRecentPublished()->id }}">
        <button type="submit" class="btn btn-primary">Click here to accept the new terms of service</button>
    </form>

</div>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>


    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('dashboard') }}">{{ __('Dashboard') }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('terms_of_service.index') }}">{{ __('Manage terms of service') }}</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @if(auth()->user() && !auth()->user()->hasAcceptedLatestTermsOfService())
            @include('layouts._accept_terms_of_service_prompt')
        @endif
        @if(session()->has('success'))
            @foreach((session('success') ?? []) as $message)
                <div class="alert alert-info">
                    {{ $message }}
                </div>
            @endforeach
        @endif
        @yield('content')
    </main>
</div>

</body>
</html>